const fs = require('fs');
const path = require('path');

const dirs = [
  "apps/web/src/app/(public)/partners",
  "apps/web/src/app/(public)/careers",
  "apps/web/src/app/(public)/data-processing",
  "apps/web/src/app/(public)/accessibility",
  "apps/web/src/app/(public)/status",
  "apps/web/src/app/(auth)/verify-email",
  "apps/web/src/app/(auth)/verify-phone",
  "apps/web/src/app/(auth)/suspended",
  "apps/web/src/app/(auth)/session-expired",
  "apps/web/src/app/(dashboard)/workspace",
  "apps/web/src/app/(dashboard)/voting",
  "apps/web/src/app/(dashboard)/resolutions",
  "apps/web/src/app/(dashboard)/dividends",
  "apps/web/src/app/(dashboard)/surplus",
  "apps/web/src/app/(dashboard)/investments",
  "apps/web/src/app/(dashboard)/marketplace",
  "apps/web/src/app/(dashboard)/fraud-risk",
  "apps/web/src/app/(dashboard)/developer",
  "apps/web/src/app/(dashboard)/multi-tenant",
  "apps/web/src/app/(dashboard)/data-governance",
  "apps/web/src/app/(dashboard)/platform-admin",
  "apps/web/src/app/(dashboard)/federation",
  "apps/web/src/app/api/internal",
  "apps/web/src/components/governance",
  "apps/web/src/components/voting",
  "apps/web/src/components/dividends",
  "apps/web/src/components/surplus",
  "apps/web/src/components/investments",
  "apps/web/src/components/marketplace",
  "apps/web/src/components/developer",
  "apps/web/src/components/platform-admin",
  "apps/web/src/features/dividends",
  "apps/web/src/features/surplus",
  "apps/web/src/features/investments",
  "apps/web/src/features/marketplace",
  "apps/web/src/features/fraud-risk",
  "apps/web/src/features/federation",
  "apps/web/src/features/platform-admin",
  "apps/web/src/features/experimentation",
  "apps/web/src/lib/bff",
  "apps/web/src/lib/experiments",
  "apps/web/src/lib/offline",
  "apps/web/src/server/projections",
  "apps/api/src/core/privacy",
  "apps/api/src/core/compliance",
  "apps/api/src/core/observability",
  "apps/api/src/core/events",
  "apps/api/src/core/queues",
  "apps/api/src/gateway/bff-mobile",
  "apps/api/src/gateway/internal-gateway",
  "apps/api/src/modules/sessions",
  "apps/api/src/modules/profiles",
  "apps/api/src/modules/federations",
  "apps/api/src/modules/obligations",
  "apps/api/src/modules/payment-disputes",
  "apps/api/src/modules/refunds-reversals",
  "apps/api/src/modules/reconciliation-rules",
  "apps/api/src/modules/budgets",
  "apps/api/src/modules/forecasts",
  "apps/api/src/modules/dividends",
  "apps/api/src/modules/surplus",
  "apps/api/src/modules/investments",
  "apps/api/src/modules/governance",
  "apps/api/src/modules/voting",
  "apps/api/src/modules/resolutions",
  "apps/api/src/modules/media",
  "apps/api/src/modules/content",
  "apps/api/src/modules/cms",
  "apps/api/src/modules/fraud-risk",
  "apps/api/src/modules/anomaly-detection",
  "apps/api/src/modules/data-governance",
  "apps/api/src/modules/partner-apis",
  "apps/api/src/modules/feature-flags",
  "apps/api/src/modules/experiments",
  "apps/api/src/modules/platform-admin",
  "apps/api/src/modules/developer-platform",
  "apps/api/src/modules/observability",
  "apps/api/src/jobs/audit",
  "apps/api/src/jobs/archival",
  "apps/api/src/jobs/cleanup",
  "apps/worker/src/jobs/ocr",
  "apps/worker/src/jobs/fraud-scoring",
  "apps/worker/src/jobs/anomaly-detection",
  "apps/worker/src/jobs/projections",
  "apps/worker/src/jobs/bank-reconciliations",
  "apps/worker/src/jobs/retention",
  "apps/worker/src/jobs/archival",
  "apps/worker/src/jobs/audit-archival",
  "apps/worker/src/jobs/backups",
  "apps/worker/src/utils",
  "apps/mobile/src/screens/documents",
  "apps/mobile/src/screens/settings",
  "apps/mobile/src/theme",
  "apps/admin/src/modules/tenants",
  "apps/admin/src/modules/subscriptions",
  "apps/admin/src/modules/billing",
  "apps/admin/src/modules/support",
  "apps/admin/src/modules/compliance",
  "apps/admin/src/modules/audit",
  "apps/admin/src/modules/feature-flags",
  "apps/admin/src/modules/experiments",
  "apps/admin/src/modules/incidents",
  "apps/admin/src/modules/health",
  "apps/admin/src/modules/platform-settings",
  "apps/admin/src/config",
  "packages/workflows",
  "packages/events",
  "packages/analytics",
  "packages/search",
  "packages/observability",
  "packages/feature-flags",
  "services/auth-service",
  "services/document-service",
  "services/fraud-risk-service",
  "services/partner-integration-service",
  "infrastructure/kubernetes/production",
  "infrastructure/messaging/kafka",
  "infrastructure/messaging/rabbitmq",
  "infrastructure/disaster-recovery",
  "infrastructure/secrets",
  "infrastructure/certificates",
  "infrastructure/multi-region",
  "docs/governance",
  "docs/release",
  "docs/decisions",
  "docs/enterprise",
  "database/archival",
  "database/views",
  "database/materialized-views",
  "database/procedures",
  "database/performance",
  "data/imports",
  "data/exports",
  "data/templates",
  "data/migrations",
  "data/samples",
  "data/retention",
  "qa/test-data",
  "qa/mocks",
  "qa/security",
  "security/pentest",
  "security/compliance-evidence"
];

for (const dir of dirs) {
  const p = path.join(process.cwd(), dir);
  if (!fs.existsSync(p)) {
    fs.mkdirSync(p, { recursive: true });
    fs.writeFileSync(path.join(p, '.gitkeep'), '');
  }
}

const files = [
  "apps/admin/package.json"
];

for (const file of files) {
  const p = path.join(process.cwd(), file);
  if (!fs.existsSync(p)) {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, '{}');
  }
}

console.log('Phase 3 Scaffold Complete');
