const fs = require('fs');
const path = require('path');

const dirs = [
  "apps/web/src/app/(public)/blog",
  "apps/web/src/app/(public)/resources",
  "apps/web/src/app/(public)/faq",
  "apps/web/src/app/(public)/help-centre",
  "apps/web/src/app/(public)/testimonials",
  "apps/web/src/app/(public)/demo",
  "apps/web/src/app/(public)/security",
  "apps/web/src/app/(public)/compliance",
  "apps/web/src/app/(dashboard)/analytics",
  "apps/web/src/app/(dashboard)/communications",
  "apps/web/src/app/(dashboard)/templates",
  "apps/web/src/app/(dashboard)/subscriptions",
  "apps/web/src/app/(dashboard)/billing",
  "apps/web/src/app/(dashboard)/invoicing",
  "apps/web/src/app/(dashboard)/collections",
  "apps/web/src/app/(dashboard)/support",
  "apps/web/src/app/(dashboard)/ai-assistant",
  "apps/web/src/app/(dashboard)/automations",
  "apps/web/src/app/(dashboard)/search",
  "apps/web/src/app/(dashboard)/branches",
  "apps/web/src/app/(dashboard)/compliance",
  "apps/web/src/app/(dashboard)/privacy-consent",
  "apps/web/src/app/(dashboard)/social-media-integration",
  "apps/web/src/app/api/ai",
  "apps/web/src/app/api/search",
  "apps/web/src/app/api/webhooks",
  "apps/web/src/app/api/status",
  "apps/web/src/components/analytics",
  "apps/web/src/components/communications",
  "apps/web/src/components/subscriptions",
  "apps/web/src/components/billing",
  "apps/web/src/components/support",
  "apps/web/src/components/ai",
  "apps/web/src/components/automations",
  "apps/web/src/components/compliance",
  "apps/web/src/components/privacy",
  "apps/web/src/features/analytics",
  "apps/web/src/features/communications",
  "apps/web/src/features/templates",
  "apps/web/src/features/subscriptions",
  "apps/web/src/features/billing",
  "apps/web/src/features/invoicing",
  "apps/web/src/features/collections",
  "apps/web/src/features/support",
  "apps/web/src/features/ai-assistant",
  "apps/web/src/features/automations",
  "apps/web/src/features/privacy-consent",
  "apps/web/src/features/compliance",
  "apps/web/src/features/search",
  "apps/web/src/features/branches",
  "apps/web/src/features/social-media",
  "apps/web/src/lib/analytics",
  "apps/web/src/lib/monitoring",
  "apps/web/src/lib/observability",
  "apps/web/src/lib/ai",
  "apps/web/src/lib/feature-flags",
  "apps/web/src/lib/privacy",
  "apps/web/src/lib/compliance",
  "apps/web/src/lib/search",
  "apps/web/src/server/events",
  "apps/web/src/server/queues",
  "apps/web/src/server/schedulers",
  "apps/web/src/server/integrations",
  "apps/web/src/content/blog",
  "apps/web/src/content/resources",
  "apps/web/src/content/legal",
  "apps/web/tests/accessibility",
  "apps/web/tests/visual-regression",
  "apps/web/tests/performance",
  "apps/api/src/gateway/api-gateway",
  "apps/api/src/gateway/bff-web",
  "apps/api/src/gateway/webhooks",
  "apps/api/src/modules/subscriptions",
  "apps/api/src/modules/billing",
  "apps/api/src/modules/invoices",
  "apps/api/src/modules/collections",
  "apps/api/src/modules/branches",
  "apps/api/src/modules/dashboards",
  "apps/api/src/modules/analytics",
  "apps/api/src/modules/messaging",
  "apps/api/src/modules/email",
  "apps/api/src/modules/sms",
  "apps/api/src/modules/whatsapp",
  "apps/api/src/modules/push",
  "apps/api/src/modules/templates",
  "apps/api/src/modules/support",
  "apps/api/src/modules/tickets",
  "apps/api/src/modules/knowledge-base",
  "apps/api/src/modules/search",
  "apps/api/src/modules/search-indexing",
  "apps/api/src/modules/ai",
  "apps/api/src/modules/automations",
  "apps/api/src/modules/workflow-engine",
  "apps/api/src/modules/rules-engine",
  "apps/api/src/modules/privacy-consent",
  "apps/api/src/modules/data-retention",
  "apps/api/src/modules/data-import",
  "apps/api/src/modules/data-export",
  "apps/api/src/modules/integrations",
  "apps/api/src/modules/webhooks",
  "apps/api/src/modules/social-media",
  "apps/api/src/modules/compliance",
  "apps/api/src/modules/activity-streams",
  "apps/api/src/jobs/billing",
  "apps/api/src/jobs/communications",
  "apps/api/src/jobs/analytics",
  "apps/api/src/jobs/retention",
  "apps/api/src/jobs/search-indexing",
  "apps/api/src/database/views",
  "apps/api/src/database/scripts",
  "apps/worker/src/jobs/whatsapp",
  "apps/worker/src/jobs/push",
  "apps/worker/src/jobs/follow-ups",
  "apps/worker/src/jobs/scheduled-reports",
  "apps/worker/src/jobs/report-delivery",
  "apps/worker/src/jobs/billing",
  "apps/worker/src/jobs/subscription-renewals",
  "apps/worker/src/jobs/analytics-aggregation",
  "apps/worker/src/jobs/search-indexing",
  "apps/worker/src/jobs/data-export",
  "apps/worker/src/jobs/cleanup",
  "apps/worker/src/schedulers",
  "apps/worker/src/events",
  "apps/mobile/src/screens/contributions",
  "apps/mobile/src/screens/communications",
  "apps/mobile/src/screens/meetings",
  "apps/mobile/src/screens/support",
  "apps/mobile/src/screens/ai-assistant",
  "apps/mobile/src/offline",
  "apps/docs-site/src",
  "packages/privacy",
  "packages/workflows",
  "packages/events",
  "packages/analytics",
  "packages/search",
  "packages/observability",
  "packages/feature-flags",
  "services/notification-service",
  "services/search-service",
  "services/billing-service",
  "services/reporting-service",
  "services/ai-service",
  "services/integration-service",
  "infrastructure/docker/redis",
  "infrastructure/docker/object-storage",
  "infrastructure/docker/search",
  "infrastructure/kubernetes/development",
  "infrastructure/kubernetes/staging",
  "infrastructure/kubernetes/uat",
  "infrastructure/messaging/redis-streams",
  "infrastructure/cdn",
  "infrastructure/backups",
  "infrastructure/runbooks",
  "docs/design-system",
  "docs/privacy",
  "docs/compliance",
  "docs/operations",
  "docs/support",
  "docs/product",
  "docs/qa",
  "content/marketing",
  "content/blog",
  "content/resources",
  "content/emails",
  "content/sms",
  "content/whatsapp",
  "content/legal",
  "qa/test-plans",
  "qa/fixtures",
  "qa/accessibility",
  "qa/performance",
  "qa/regression",
  "security/standards",
  "security/compliance-evidence",
  "security/vendor-assessments",
  "security/risk-register"
];

for (const dir of dirs) {
  const p = path.join(process.cwd(), dir);
  if (!fs.existsSync(p)) {
    fs.mkdirSync(p, { recursive: true });
    // adding gitkeep ensures tools tracking directory structure notice it
    fs.writeFileSync(path.join(p, '.gitkeep'), '');
  }
}

// Ensure the new package.json for docs-site is created
const files = [
  "apps/docs-site/package.json"
];

for (const file of files) {
  const p = path.join(process.cwd(), file);
  if (!fs.existsSync(p)) {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, '{}');
  }
}

console.log('Phase 2 Scaffold Complete');
